import type { PricingPlan } from "@/components/sections/pricing-section";

// Edit prices and task lists here. A feature starting with "## " is a room
// heading; everything else is a task under the heading above it.

export const homeCleaningPlans: PricingPlan[] = [
  {
    name: "Silver",
    nameClassName: "text-plan-silver",
    price: { type: "monthly", amount: 150 },
    features: [
      "## All Areas",
      "Vacuum and steam mop all floors",
      "Empty all garbage & recycling",
      "Cleaning & polish all mirrors",
      "Dust reachable surfaces",
      "## Kitchen",
      "Wipe counters & backsplash",
      "Disinfect & polish sinks and taps",
      "Wipe exterior of appliances",
      "Wipe kitchen cabinets on the outside",
      "Wipe oven front and stove top",
      "## Bedrooms",
      "Make the beds",
      "Dust all furniture",
      "General organizing",
      "## Bathrooms",
      "Wipe vanity, sinks & all taps",
      "Disinfect and clean toilets (inside & out)",
      "Wipe bathtub and shower stall",
      "## Living Room",
      "Dust Furniture",
      "General organizing",
    ],
  },
  {
    name: "Gold",
    nameClassName: "text-plan-gold",
    price: { type: "monthly", amount: 235 },
    features: [
      "## All Areas",
      "Vacuum and steam mop all floors",
      "Empty all garbage & recycling",
      "Cleaning & polish all mirrors",
      "Dust reachable surfaces",
      "Wipe cupboard doors & window sills",
      "Clean baseboards",
      "Clean light switches and door knobs",
      "Dust & clean window ledges",
      "Wipe all doors",
      "## Kitchen",
      "Wipe counters & backsplash",
      "Disinfect & polish sinks and taps",
      "Wipe exterior of appliances",
      "Wipe kitchen cabinets on the outside",
      "Wipe oven front and stove top",
      "## Bedrooms",
      "Make the beds",
      "Dust all furniture",
      "General organizing",
      "Dust lampshades, picture frames, etc.",
      "## Bathrooms",
      "Wipe vanity, sinks & all taps",
      "Disinfect and clean toilets (inside & out)",
      "Clean all chrome fixtures",
      "Wipe bathtub and shower stall",
      "Scrub the bathtub & shower stall",
      "## Living Room",
      "Dust Furniture",
      "Dust electronics",
      "Vacuum sofas",
      "General organizing",
    ],
  },
  {
    name: "Diamond",
    nameClassName: "text-plan-diamond",
    price: { type: "monthly", amount: 280 },
    features: [
      "## All Areas",
      "Vacuum and steam mop all floors",
      "Empty all garbage & recycling",
      "Cleaning & polish all mirrors",
      "Dust reachable surfaces",
      "Wipe cupboard doors & window sills",
      "Clean baseboards",
      "Clean light switches and door knobs",
      "Dust & clean window ledges",
      "Wipe all doors",
      "Clean cabinets and drawers (inside)",
      "Clean walls",
      "Clean windows (inside)",
      "## Kitchen",
      "Wipe counters & backsplash",
      "Disinfect & polish sinks and taps",
      "Wipe exterior of appliances",
      "Wipe kitchen cabinets on the outside",
      "Wipe oven front and stove top",
      "Clean inside over and fridge",
      "Clean inside microwave",
      "Clean the range hood",
      "## Bedrooms",
      "Make the beds",
      "Dust all furniture",
      "General organizing",
      "Dust lampshades, picture frames, etc.",
      "## Bathrooms",
      "Wipe vanity, sinks & all taps",
      "Disinfect and clean toilets (inside & out)",
      "Clean all chrome fixtures",
      "Wipe bathtub and shower stall",
      "Scrub the bathtub & shower stall",
      "Clean inside the bathroom cabinets",
      "Clean the tiles and baseboards",
      "## Living Room",
      "Dust Furniture",
      "Dust electronics",
      "Vacuum sofas",
      "General organizing",
      "Wipe the fireplace",
      "## Balcony",
      "Sweeping of balcony",
      "Dustin the railings",
    ],
  },
];

export const carDetailingPlans: PricingPlan[] = [
  {
    name: "Interior Cleaning",
    price: { type: "range", from: 130, to: 250, plainCurrency: true },
    boldFeatures: true,
    features: [
      "Passenger Car - $130",
      "Medium SUV and Pick-Up Trucks - $180",
      "Large SUV and Minivan - $250",
    ],
  },
  {
    name: "Exterior Cleaning",
    price: { type: "range", from: 95, to: 120 },
    boldFeatures: true,
    features: [
      "Passenger Car - $95",
      "Medium SUV and Pick-Up Trucks - $110",
      "Large SUV and Minivan - $120",
    ],
  },
  {
    name: "Interior & Exterior - Complete Detail",
    price: { type: "range", from: 250, to: 425 },
    boldFeatures: true,
    features: [
      "Passenger Car - $250",
      "Medium SUV and Pick-Up Trucks - $350",
      "Large SUV and Minivan - $425",
    ],
  },
];
